In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
tensor = torch.rand(3, 4, 5)
tensor

tensor([[[0.2922, 0.6851, 0.1807, 0.0146, 0.5522],
         [0.7022, 0.5452, 0.8132, 0.8634, 0.0019],
         [0.4158, 0.1736, 0.9482, 0.1059, 0.8269],
         [0.5824, 0.3399, 0.0150, 0.3603, 0.5587]],

        [[0.6962, 0.6374, 0.8545, 0.6656, 0.2539],
         [0.0347, 0.2359, 0.1748, 0.4120, 0.4091],
         [0.8494, 0.6930, 0.5555, 0.4926, 0.5834],
         [0.4520, 0.5411, 0.1758, 0.1972, 0.6934]],

        [[0.5529, 0.8098, 0.6976, 0.9764, 0.4835],
         [0.9097, 0.5312, 0.9374, 0.0434, 0.9054],
         [0.2128, 0.1515, 0.8075, 0.7585, 0.9312],
         [0.0384, 0.7919, 0.8043, 0.3456, 0.1959]]])

In [3]:
# 2. Выведите его форму (shape)
tensor.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
tensor_reshape = tensor.reshape(6, 10)
tensor_reshape

tensor([[0.2922, 0.6851, 0.1807, 0.0146, 0.5522, 0.7022, 0.5452, 0.8132, 0.8634,
         0.0019],
        [0.4158, 0.1736, 0.9482, 0.1059, 0.8269, 0.5824, 0.3399, 0.0150, 0.3603,
         0.5587],
        [0.6962, 0.6374, 0.8545, 0.6656, 0.2539, 0.0347, 0.2359, 0.1748, 0.4120,
         0.4091],
        [0.8494, 0.6930, 0.5555, 0.4926, 0.5834, 0.4520, 0.5411, 0.1758, 0.1972,
         0.6934],
        [0.5529, 0.8098, 0.6976, 0.9764, 0.4835, 0.9097, 0.5312, 0.9374, 0.0434,
         0.9054],
        [0.2128, 0.1515, 0.8075, 0.7585, 0.9312, 0.0384, 0.7919, 0.8043, 0.3456,
         0.1959]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
int_tensor = torch.IntTensor(10)
int_tensor

tensor([-948183872,      21944,         27,          0,         -1,   16843009,
         678913390, 1142959146, 1667855973, 1679834981], dtype=torch.int32)

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
mult_tensor = tensor_reshape * int_tensor
mult_tensor

tensor([[-2.7704e+08,  1.5033e+04,  4.8783e+00,  0.0000e+00, -5.5222e-01,
          1.1827e+07,  3.7015e+08,  9.2946e+08,  1.4400e+09,  3.1519e+06],
        [-3.9426e+08,  3.8101e+03,  2.5603e+01,  0.0000e+00, -8.2686e-01,
          9.8086e+06,  2.3079e+08,  1.7164e+07,  6.0098e+08,  9.3855e+08],
        [-6.6017e+08,  1.3987e+04,  2.3071e+01,  0.0000e+00, -2.5388e-01,
          5.8521e+05,  1.6014e+08,  1.9974e+08,  6.8721e+08,  6.8717e+08],
        [-8.0538e+08,  1.5206e+04,  1.4999e+01,  0.0000e+00, -5.8342e-01,
          7.6124e+06,  3.6738e+08,  2.0099e+08,  3.2887e+08,  1.1648e+09],
        [-5.2429e+08,  1.7771e+04,  1.8835e+01,  0.0000e+00, -4.8355e-01,
          1.5322e+07,  3.6062e+08,  1.0714e+09,  7.2339e+07,  1.5209e+09],
        [-2.0177e+08,  3.3243e+03,  2.1804e+01,  0.0000e+00, -9.3122e-01,
          6.4621e+05,  5.3762e+08,  9.1928e+08,  5.7635e+08,  3.2914e+08]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
torch.mm(mult_tensor, torch.transpose(mult_tensor, 0 , 1))

tensor([[3.1513e+18, 1.0791e+18, 1.4195e+18, 1.0232e+18, 1.3837e+18, 1.9403e+18],
        [1.0791e+18, 1.4511e+18, 1.3586e+18, 1.6968e+18, 1.7794e+18, 8.7470e+17],
        [1.4195e+18, 1.3586e+18, 1.4458e+18, 1.6571e+18, 1.7127e+18, 1.0252e+18],
        [1.0232e+18, 1.6968e+18, 1.6571e+18, 2.2891e+18, 2.5656e+18, 1.1177e+18],
        [1.3837e+18, 1.7794e+18, 1.7127e+18, 2.5656e+18, 3.8713e+18, 1.8268e+18],
        [1.9403e+18, 8.7470e+17, 1.0252e+18, 1.1177e+18, 1.8268e+18, 1.6153e+18]])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
args = torch.tensor([1., 1., 1.])
x = torch.tensor([1., 1., 1.], requires_grad=True)
z = torch.tensor([0.5, 0.5, 0.5], requires_grad=True)
t = torch.tensor([2., 2., 2.], requires_grad=True)

y = x ** 3 + z - 75 * t

y.backward(gradient=args)
x.grad, z.grad, t.grad

(tensor([3., 3., 3.]), tensor([1., 1., 1.]), tensor([-75., -75., -75.]))

In [9]:
# 8. Создайте единичный тензор размера 5x6
ones_tensor = torch.ones((5, 6))
ones_tensor

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
# 9. Переведите его в формат numpy
np_ones_tensor = ones_tensor.numpy()
np_ones_tensor

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)